from .test_jmdict_entry import JMdictEntryTestCase
from .test_jmdict_kanji import JMdictKanjiTestCase
from .test_jmdict_reading import JMdictReadingTestCase
from .test_jmdict_sense import JMdictSenseTestCase
from .test_jmdict_glossary import JMdictGlossaryTestCase