# Generated by Django 4.1.4 on 2023-01-09 09:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JMdictEntry',
            fields=[
                ('ent_seq', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JMdictSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictentry')),
            ],
        ),
        migrations.CreateModel(
            name='JMdictReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.TextField()),
                ('no_kanji', models.BooleanField()),
                ('restrictions', models.TextField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('priorities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8), size=8)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictentry')),
            ],
        ),
        migrations.CreateModel(
            name='JMdictKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.TextField()),
                ('information', models.TextField(blank=True, null=True)),
                ('priorities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8), size=8)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictentry')),
            ],
        ),
        migrations.CreateModel(
            name='JMdictGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.TextField(blank=True, null=True)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictsense')),
            ],
        ),
    ]
