# Generated by Django 4.1.4 on 2023-01-16 11:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JMdictEntry',
            fields=[
                ('ent_seq', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JMdictSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xreferences', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('antonyms', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('parts_of_speech', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('misc', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('dialects', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('information', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictentry')),
            ],
        ),
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('radical', models.TextField()),
                ('strokes', models.IntegerField()),
                ('meaning', models.TextField()),
                ('reading', models.TextField()),
                ('position', models.TextField(blank=True)),
                ('frequency', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.TextField()),
                ('strokes', models.IntegerField()),
                ('radicals', models.ManyToManyField(to='app.radical')),
            ],
        ),
        migrations.CreateModel(
            name='JMdictSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('language', models.TextField(blank=True)),
                ('partial', models.BooleanField(blank=True)),
                ('waseieigo', models.BooleanField(blank=True)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictsense')),
            ],
        ),
        migrations.CreateModel(
            name='JMdictReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('no_kanji', models.BooleanField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('information', models.TextField(blank=True)),
                ('priorities', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictentry')),
            ],
        ),
        migrations.CreateModel(
            name='JMdictKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('information', models.TextField(blank=True)),
                ('priorities', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictentry')),
            ],
        ),
        migrations.CreateModel(
            name='JMdictGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.TextField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('type', models.TextField(blank=True)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jmdictsense')),
            ],
        ),
    ]
