# Generated by Django 4.1.4 on 2023-01-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
