# Generated by Django 4.1.4 on 2023-01-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpcore', '0002_nullable_radical_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmdictglossary',
            name='sense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jglossary', to='jpcore.jmdictsense'),
        ),
        migrations.AlterField(
            model_name='jmdictkanji',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jkanji', to='jpcore.jmdictentry'),
        ),
        migrations.AlterField(
            model_name='jmdictreading',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jreading', to='jpcore.jmdictentry'),
        ),
        migrations.AlterField(
            model_name='jmdictsense',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jsense', to='jpcore.jmdictentry'),
        ),
        migrations.AlterField(
            model_name='jmdictsource',
            name='sense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jsource', to='jpcore.jmdictsense'),
        ),
    ]
