# Generated by Django 4.1.4 on 2023-02-21 00:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpcore', '0003_jmdict_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KDVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deroo', models.TextField(blank=True)),
                ('jis208', models.TextField(blank=True)),
                ('jis212', models.TextField(blank=True)),
                ('jis213', models.TextField(blank=True)),
                ('nelson_c', models.TextField(blank=True)),
                ('halpern_njecd', models.TextField(blank=True)),
                ('oneill', models.TextField(blank=True)),
                ('sh', models.TextField(blank=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kvariant', to='jpcore.kdkanji')),
            ],
        ),
        migrations.CreateModel(
            name='KDReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_pinyin', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('ko_romanized', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('ko_hangul', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('vi_chu', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('ja_on', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('ja_kun', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('ja_nanori', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdreading', to='jpcore.kdkanji')),
            ],
        ),
        migrations.CreateModel(
            name='KDRadical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classical', models.TextField()),
                ('nelson', models.TextField()),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdradical', to='jpcore.kdkanji')),
            ],
        ),
        migrations.CreateModel(
            name='KDQueryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip', models.TextField()),
                ('sh_descriptor', models.TextField()),
                ('four_corner', models.TextField()),
                ('deroo', models.TextField()),
                ('misclass_pos', models.TextField(blank=True)),
                ('misclass_strokes', models.TextField(blank=True)),
                ('misclass_strokes_diff', models.TextField(blank=True)),
                ('misclass_strokes_pos', models.TextField(blank=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdquerycode', to='jpcore.kdkanji')),
            ],
        ),
        migrations.CreateModel(
            name='KDMisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.TextField(blank=True)),
                ('jlpt', models.TextField(blank=True)),
                ('strokes', models.TextField()),
                ('frequency', models.TextField(blank=True)),
                ('radical_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdmisc', to='jpcore.kdkanji')),
            ],
        ),
        migrations.CreateModel(
            name='KDMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdmeaning', to='jpcore.kdkanji')),
            ],
        ),
        migrations.CreateModel(
            name='KDIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_people', models.TextField(blank=True)),
                ('crowley', models.TextField(blank=True)),
                ('gakken', models.TextField(blank=True)),
                ('halpern_kkd', models.TextField(blank=True)),
                ('halpern_kkld', models.TextField(blank=True)),
                ('halpern_kkld_2nd', models.TextField(blank=True)),
                ('halpern_njecd', models.TextField(blank=True)),
                ('henshall', models.TextField(blank=True)),
                ('henshall3', models.TextField(blank=True)),
                ('heisig', models.TextField(blank=True)),
                ('heisig6', models.TextField(blank=True)),
                ('jf_cards', models.TextField(blank=True)),
                ('kanji_in_context', models.TextField(blank=True)),
                ('kodansha_compact', models.TextField(blank=True)),
                ('maniette', models.TextField(blank=True)),
                ('moro', models.TextField(blank=True)),
                ('moro_volume', models.TextField(blank=True)),
                ('moro_page', models.TextField(blank=True)),
                ('nelson_c', models.TextField(blank=True)),
                ('nelson_n', models.TextField(blank=True)),
                ('oneill_names', models.TextField(blank=True)),
                ('oneill_kk', models.TextField(blank=True)),
                ('sakade', models.TextField(blank=True)),
                ('sh_kk', models.TextField(blank=True)),
                ('sh_kk2', models.TextField(blank=True)),
                ('tutt_cards', models.TextField(blank=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdindex', to='jpcore.kdkanji')),
            ],
        ),
        migrations.CreateModel(
            name='KDCodePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucs', models.TextField(blank=True)),
                ('jis208', models.TextField(blank=True)),
                ('jis212', models.TextField(blank=True)),
                ('jis213', models.TextField(blank=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdcodepoint', to='jpcore.kdkanji')),
            ],
        ),
    ]
