# Generated by Django 4.1.4 on 2023-02-24 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpcore', '0004_kanjidict_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdvariant',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdvariant', to='jpcore.kdkanji'),
        ),
    ]
