# Generated by Django 4.1.4 on 2023-03-05 23:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpcore', '0005_kdvariant_typo_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdquerycode',
            name='misclass_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='kdquerycode',
            name='misclass_strokes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='kdquerycode',
            name='misclass_strokes_diff',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='kdquerycode',
            name='misclass_strokes_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.CreateModel(
            name='SkipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('main', models.IntegerField()),
                ('sub', models.IntegerField()),
                ('kanji', models.ManyToManyField(to='jpcore.kdkanji')),
            ],
            options={
                'unique_together': {('category', 'main', 'sub')},
            },
        ),
    ]
