# Generated by Django 4.1.4 on 2023-05-01 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpcore', '0006_improved_skip_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualCloseness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sed', models.DecimalField(decimal_places=3, max_digits=4)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcloseness', to='jpcore.kdkanji')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrelated', to='jpcore.kdkanji')),
            ],
        ),
    ]
